### ISSUE TITLE
Rename mct-minibuffer-mode back to mct-mode?

### ISSUE THREAD

**Issue by minad** [protesilaos/mct#4]
In the light of the recent restructuring, which is good btw. It is better to keep this package simple.

**Comment by protesilaos** [comment]
Thank you @minad!  I just pushed the change, but it seems that the mirror is not synced yet.  It may take an extra minute.

```
commit 47f1a4aa8397795cfe68dac75bd8007d8550bc6c
Author: Protesilaos Stavrou <info@protesilaos.com>
Date:   Wed Mar 29 19:17:05 2023 +0300

    Rename mct-minibuffer-mode to mct-mode
    
    Thanks to Daniel Mendler for informing me about this in issue 4 on the
    GitHub mirror: <https://github.com/protesilaos/mct/issues/4>.

 README.org | 26 +++++++++++++++-----------
 mct.el     | 47 ++++++++++++++++++++++++++---------------------
 2 files changed, 41 insertions(+), 32 deletions(-)
```

**Comment by minad** [comment]
Thanks, how do you synchronize your mirrors?

**Comment by protesilaos** [comment]
I am not efficient with this...  I add them as a remote and push to it each time.  The GitLab ==> GitHub is done automatically by a one-off setup per repo.

I wanted to do this with hooks or something like that, but I did not find the right documentation for the post-push phase.  There is `githooks(5)`, though I did not find what I was looking for last time I checked.
